---
language: python
python:
  - "3.6"

env:
  global:
    - IMAGE="opensplit/backend"

services:
  - docker

install:
  - pip install pipenv flake8
  - pipenv install

script:
  - cp config.py.example config.py
  - flake8 .
  - ./test.py
  - docker build -t $IMAGE .

after_success:

deploy:
  # deploy develop to the staging environment
  - provider: script
    script: bash scripts/deploy.sh staging
    on:
      branch: developmoent
  # deploy master to production
  - provider: script
    script: bash scripts/deploy.sh production
    on:
      branch: master
