---
language: python
python:
  - "3.6"

env:
  global:
    - IMAGE="opensplit/backend"

services:
  - docker

install:
  - pip install pipenv flake8
  - pipenv install

script:
  - cp config.py.example config.py
  - flake8 .
  - ./test.py
  - docker build -t $IMAGE .

after_success:
  - test $TRAVIS_BRANCH = "master" && docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push $IMAGE
