---
language: python
python:
  - "3.6"

services:
  - docker

env:
  global:
    - IMAGE="opensplit/backend"

branches:
  only:
    - master
    - development

install:
  - pip install pipenv flake8
  - pipenv install

script:
  - cp config.py.example config.py
  - flake8 .
  - ./test.py

after_success:
  - if [ ${TRAVIS_BRANCH} == master ] ; then IMAGE_TAG=stable; else IMAGE_TAG=development; fi
  - docker build -t $IMAGE:$IMAGE_TAG .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $IMAGE:$IMAGE_TAG

#deploy:
#  # deploy develop to the staging environment
#  - provider: script
#    script: bash scripts/deploy.sh staging
#    on:
#      branch: development
#
#  # deploy master to production
#  - provider: script
#    script: bash scripts/deploy.sh production
#    on:
#      branch: master
#