---
language: python
python:
  - "3.6"

services:
  - docker

git:
  depth: false

env:
  global:
    - IMAGE="opensplit/backend"

branches:
  only:
    - master
    - development

install:
  - pip install pipenv flake8
  - pipenv install
  - cp config.py.example config.py
  - if [ ${TRAVIS_BRANCH} == master ] ; then IMAGE_TAG=stable; else IMAGE_TAG=development; fi

script:
  - flake8 .
  - ./test.py
  - docker build -t $IMAGE:$IMAGE_TAG .

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $IMAGE:$IMAGE_TAG

deploy:
 - provider: script
   script: curl -X POST $WEBHOOK_DEV
   on:
     branch: development

 - provider: script
   script: curl -X POST $WEBHOOK_PROD
   on:
     branch: master

