"""empty message

Revision ID: a8bef86f4475
Revises: b779c40aad69
Create Date: 2018-12-21 22:08:03.005305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8bef86f4475'
down_revision = 'b779c40aad69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.create_foreign_key(None, 'history', 'expense', ['expense_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.create_foreign_key(None, 'history', 'user', ['expense_id'], ['id'])
    # ### end Alembic commands ###
